pull_request_rules:
  - name: Automatically merge PRs from dependabot
    conditions:
      - and:
        - author~=^dependabot(|-preview)\[bot\]$
        - check-success=CodeQL
        - check-success=build
        - check-success=build (16.x)
        - check-success=build (18.x)
        - check-success=Analyze (javascript)
        - check-success=Analyze (java)
        - check-success=[MoviesColl] SonarCloud Code Analysis
    actions:
      merge:
        method: merge
  - name: Delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch:
