version: "3"
services:
  spring-app:
    image: "eulodos/movies-coll-backend"
    environment:
      - TMDB_API_KEY=${TMDB_API_KEY}
    ports:
      - "8080:8080"
    networks:
      - my-network
  angular-app:
    image: "eulodos/movies-coll-frontend"
    ports:
      - "4200:80"
    networks:
      - my-network
    depends_on:
      - spring-app
networks:
  my-network:
